(deftheme jeremiah
  "Created 2021-05-06.")

(custom-theme-set-variables
 'jeremiah
 '(ansi-color-names-vector ["#272b34" "#c60013" "#8cc610" "#eea806" "#088afb" "#ec3691" "#1ee079" "#f6f2f3"])
 '(awesome-tray-mode-line-active-color "#2fafff")
 '(awesome-tray-mode-line-inactive-color "#323232")
 '(backup-directory-alist '((".*" . "~/.backups")))
 '(bidi-paragraph-direction 'left-to-right)
 '(browse-url-browser-function 'eww-browse-url)
 '(c-default-style '((c-mode . "k&r") (c++-mode . "java") (java-mode . "java") (awk-mode . "awk") (other . "gnu")))
 '(c-hanging-braces-alist '((block-open after) (block-close . c-snug-do-while) (statement-cont) (substatement-open after) (brace-list-open) (brace-entry-open) (extern-lang-open after) (namespace-open after) (module-open after) (composition-open after) (inexpr-class-open after) (inexpr-class-close before) (arglist-cont-nonempty)))
 '(c-offsets-alist '((substatement-open . +) (substatement-open . 0) (access-label . -) (statement-case-open . +)))
 '(compilation-scroll-output t)
 '(custom-safe-themes '("e8825f26af32403c5ad8bc983f8610a4a4786eb55e3a363fa9acb48e0677fe7e" "c1126be58e0064385f8855eef3121df368d79ca001a748e9df8fe2fb6257d353" "d8dc153c58354d612b2576fea87fe676a3a5d43bcc71170c62ddde4a1ad9e1fb" "cdd26fa6a8c6706c9009db659d2dffd7f4b0350f9cc94e5df657fa295fffec71" default))
 '(describe-char-unidata-list '(name old-name general-category canonical-combining-class bidi-class decomposition decimal-digit-value digit-value numeric-value mirrored iso-10646-comment uppercase lowercase titlecase))
 '(diary-file "~/src/gtd/diary")
 '(erc-fill-column 132)
 '(erc-hide-list '("JOIN" "PART" "QUIT"))
 '(erc-nick "jlarocco")
 '(flymake-error-bitmap '(flymake-double-exclamation-mark modus-theme-fringe-red))
 '(flymake-note-bitmap '(exclamation-mark modus-theme-fringe-cyan))
 '(flymake-warning-bitmap '(exclamation-mark modus-theme-fringe-yellow))
 '(font-lock-maximum-size nil)
 '(grep-command "grep -i -n -e ")
 '(grep-find-use-xargs 'exec-plus)
 '(grep-highlight-matches t)
 '(grep-use-null-device t)
 '(grep-use-null-filename-separator t)
 '(highlight-tail-colors '(("#2f4a00" . 0) ("#00415e" . 20)))
 '(hl-todo-keyword-faces '(("HOLD" . "#cfdf30") ("TODO" . "#feacd0") ("NEXT" . "#b6a0ff") ("THEM" . "#f78fe7") ("PROG" . "#00d3d0") ("OKAY" . "#4ae8fc") ("DONT" . "#80d200") ("FAIL" . "#ff8059") ("BUG" . "#ff8059") ("DONE" . "#44bc44") ("NOTE" . "#f0ce43") ("KLUDGE" . "#eecc00") ("HACK" . "#eecc00") ("TEMP" . "#ffcccc") ("FIXME" . "#ff9977") ("XXX+" . "#f4923b") ("REVIEW" . "#6ae4b9") ("DEPRECATED" . "#bfd9ff")))
 '(ibuffer-deletion-face 'modus-theme-mark-del)
 '(ibuffer-filter-group-name-face 'modus-theme-mark-symbol)
 '(ibuffer-marked-face 'modus-theme-mark-sel)
 '(ibuffer-title-face 'modus-theme-pseudo-header)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(lisp-mode-hook '(slime-editing-mode))
 '(org-babel-load-languages '((emacs-lisp . t) (shell . t) (lisp . t) (python . t)))
 '(org-confirm-babel-evaluate nil)
 '(org-export-use-babel t)
 '(org-indent-indentation-per-level 0)
 '(org-indent-mode-turns-off-org-adapt-indentation nil)
 '(org-src-tab-acts-natively t)
 '(package-archives '(("gnu" . "https://elpa.gnu.org/packages/") ("marmalade" . "http://marmalade-repo.org/packages/") ("melpa" . "https://melpa.org/packages/")))
 '(package-native-compile t)
 '(package-selected-packages '(paredit git-walktree magit glsl-mode ace-window diredfl ada-mode ada-ref-man ag dired-quick-sort git-timemachine farmhouse-theme erlang flycheck-pycheckers flycheck-pyflakes elpy htmlize lua-mode abyss-theme slime-docker dylan-mode julia-shell geiser gopher markdown-mode haskell-mode))
 '(pos-tip-tab-width 4)
 '(safe-local-variable-values '((Package . CCL) (Package . CL-USER) (Syntax . COMMON-LISP) (Syntax . Common-lisp) (package . CL-GDAL) (Package . CLIM-GUI) (Package . URL) (Readtable . GLISP) (Encoding . utf-8) (Package . RENDERER) (Package . CLOSURE/CLIM-DEVICE) (Package . CLIM-INTERNALS) (Syntax . Common-Lisp) (Lowercase . Yes) (Base . 10) (Package . CLIM-DEMO) (Syntax . ANSI-Common-Lisp)))
 '(scroll-bar-mode nil)
 '(shell-file-name "zsh")
 '(slime-enable-evaluate-in-emacs t)
 '(tab-width 4)
 '(text-scale-mode-step 1.125)
 '(use-file-dialog nil)
 '(vc-annotate-background nil)
 '(vc-annotate-background-mode nil)
 '(vc-annotate-color-map '((20 . "#ff8059") (40 . "#feacd0") (60 . "#f78fe7") (80 . "#f4923b") (100 . "#eecc00") (120 . "#cfdf30") (140 . "#f8dec0") (160 . "#bfebe0") (180 . "#44bc44") (200 . "#80d200") (220 . "#6ae4b9") (240 . "#4ae8fc") (260 . "#00d3d0") (280 . "#c6eaff") (300 . "#2fafff") (320 . "#79a8ff") (340 . "#00bcff") (360 . "#b6a0ff")))
 '(vc-annotate-very-old-color nil)
 '(vc-handled-backends '(git))
 '(visible-cursor t)
 '(warning-suppress-log-types '((comp)))
 '(when t)
 '(which-func-modes t)
 '(whitespace-style '(face trailing tabs empty indentation::space space-after-tab::space space-after-tab space-before-tab::space tab-mark))
 '(x-stretch-cursor t)
 '(xterm-color-names ["#000000" "#ff8059" "#44bc44" "#eecc00" "#2fafff" "#feacd0" "#00d3d0" "#a8a8a8"])
 '(xterm-color-names-bright ["#181a20" "#f4923b" "#80d200" "#cfdf30" "#79a8ff" "#f78fe7" "#4ae8fc" "#ffffff"])
 '(column-number-mode t)
 '(horizontal-scroll-bar-mode nil)
 '(menu-bar-mode nil)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(tool-bar-mode nil)
 '(transient-mark-mode nil)
 '(which-function-mode t))

(custom-theme-set-faces
 'jeremiah
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#FFFFFF" :foreground "#333333" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "UKWN" :family "JuliaMono")))))

(provide-theme 'jeremiah)
